<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2014/09/23 15:27:40
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'swift_doctrinespool' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinecleanmodelfilestask' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinebuilddbtask' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrineinsertsqltask' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinedqltask' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinebuildtask' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrinegenerateadmintask' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinebuildschematask' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinedataloadtask' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinebasetask' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinecreatemodeltables' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinebuildmodeltask' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuildsqltask' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinedropdbtask' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinedatadumptask' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinebuildfilterstask' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinebuildformstask' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinemigratetask' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrinecli' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrineformgenerator' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinecolumn' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrinegenerator' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfvalidatordoctrineunique' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfvalidatordoctrinechoice' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfdoctrinerecord' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrineroute' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sftesterdoctrine' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfformdoctrine' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinepager' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrineexception' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfwidgetformdoctrinechoice' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',
  'sfwebdebugpaneldoctrine' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfdoctrinedatabase' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfdoctrineconnectionprofiler' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrineconnectionlistener' => '/home/bashman/public_html/velocidad/lib/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',

  // project
  'baseform' => '/home/bashman/public_html/velocidad/lib/form/BaseForm.class.php',

  // project_model

  // application
  'myuser' => '/home/bashman/public_html/velocidad/apps/cantv/lib/myUser.class.php',

  // modules
);
