<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/09/23 15:27:40

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=diagnosys',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
